language: java

jobs:
  include:
    - stage: CodeQualitiy
      script: ./gradlew sonarqube

addons:
  sonarcloud:
    organization: $SONAR_USER
    token:
      secure: $SONAR_TOKEN

 jdk:
  - openjdk11